<?php
	$config['1'] = '安徽';
	$config['2'] = '北京';
	$config['3'] = '重庆';
	$config['4'] = '福建';
	$config['5'] = '甘肃';
	$config['6'] = '广东';
	$config['7'] = '广西';
	$config['8'] = '贵州';
	$config['9'] = '海南';
	$config['10'] = '河北';
	$config['11'] = '黑龙江';
	$config['12'] = '河南';
	$config['13'] = '湖北';
	$config['14'] = '湖南';
	$config['15'] = '内蒙古';
	$config['16'] = '江苏';
	$config['17'] = '江西';
	$config['18'] = '吉林';
	$config['19'] = '辽宁';
	$config['20'] = '宁夏';
	$config['21'] = '青海';
	$config['22'] = '山西';
	$config['23'] = '山东';
	$config['24'] = '上海';
	$config['25'] = '四川';
	$config['26'] = '天津';
	$config['27'] = '西藏';
	$config['28'] = '新疆';
	$config['29'] = '云南';
	$config['30'] = '浙江';
	$config['31'] = '陕西';
	$config['32'] = '台湾';
	$config['33'] = '香港';
	$config['34'] = '澳门';
	$config['35'] = '海外';
 return $config;
?>